image: Visual Studio 2017

branches:
  only:
  - master

# Don't create a build when a PR is opened
skip_branch_with_pr: true

nuget:
  disable_publish_on_pr: true
  
skip_commits:
  files:
    - 'doc/**/*.*'  

init:
- ps: git config --global core.autocrlf true

build_script:
- ps: .\build\build.ps1 -script build\build.cake

artifacts:
- path: .\build\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: IkXtar7GUlIHtb4exXwdX6TjQA52w9rP7Gw+VwawieVu/frS0nP/RHf+umjWbINk
  skip_symbols: true
  artifact: /.*\.nupkg/